### ISSUE TITLE
Workflow for signe-laval to Artsdata

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-footlight#10]
Workflow for sending signe-laval events and places to Artsdata. The basic properties are needed and are the same as tout-culture. The basic properties will enable minting of Artsdata URIs in Artsdata.

Notify @saumier when completed so he can remove the old graphs he uploaded manually with the data-to-rdf spreadsheet plugin.

**Comment by saumier** [comment]
@sahalali I think this looks good from a data point of view. I am very happy that I can stop doing my manual loads with the spreadsheet. I also think that we can wait before adding more properties in the mapping. It may be that Artsdata does not need to get all the properties in Footlight CMS. Let's keep our ears open to see if any requests from Caitlin or the clients come in for more properties.

To complete the workflows for Footlight CMS, please complete the following:
- [ ] tout-culture runs every Wednesday
- [ ] signe-laval runs every Wednesday

**Comment by sahalali** [comment]
Create two workflows for export events and places from Signe Laval and Tout Culture.
Please find the workflows URLS below:
1. https://github.com/culturecreates/artsdata-planet-footlight/blob/main/.github/workflows/export-tout-culture-entities-to-footlight.yml
2. https://github.com/culturecreates/artsdata-planet-footlight/blob/main/.github/workflows/export-signe-laval-entities-to-footlight.yml

**Comment by saumier** [comment]
@sahalali Looks good. I'll remove all the old dumps and ruby code that is no longer needed.
