### ISSUE TITLE
Deploy new Footlight URI scheme lod.footlight.io

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-footlight#14]
The new URI scheme for all Footlight CMS entities should be rolled out to the Artsdata export, and carefully times with LaVitrine because it will have a big impact: on all the events LaVitrine loads will suddenly have new URIs and appear in their system for review because they will look like new events!

**Please wait for my signal** to proceed with this as I am coordinating with LaVitrine! 

All entities including events, people, places, organizations, concepts, postalAddress and any nested entities like offer. Are there any others?

For example
http://api.footlight.io/events/664518b49f43170063f9a9c3  --> http://lod.footlight.io/resource/664518b49f43170063f9a9c3 

[http://api.footlight.io/664518b49f43170063f9a9c3#Offer](https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Fapi.footlight.io%2F664518b49f43170063f9a9c3%23Offer) --> http://lod.footlight.io/resource/664518b49f43170063f9a9c3#Offer

http://api.footlight.io/places/64413e1f7a29930064510b82 --> http://lod.footlight.io/resource/64413e1f7a29930064510b82

[http://api.footlight.io/postalAddress/64413e1f7a29930064510b77](https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Fapi.footlight.io%2FpostalAddress%2F64413e1f7a29930064510b77) -->  http://lod.footlight.io/resource/64413e1f7a29930064510b77

[http://api.footlight.io/concepts/6418cdb35e4d4e0066a2f003](https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Fapi.footlight.io%2Fconcepts%2F6418cdb35e4d4e0066a2f003) --> http://lod.footlight.io/resource/2F6418cdb35e4d4e0066a2f003

The above examples are real and can be used for testing and looked up in Nebula by pasting the URI into the search box in Nebula.

**Comment by sahalali** [comment]
The configs are now updated and pushed to the branch https://github.com/culturecreates/artsdata-planet-footlight/tree/feature/change-domain-in-the-url.

**Comment by saumier** [comment]
@sahalali Please go ahead and roll out the new lod.footlight.io. I have paused the export to LaVitrine so tomorrow I can do some tests and re-link the Artsdata IDs to the new Footlight URIs.

**Comment by sahalali** [comment]
The workflows for uploading data from calendars Tout Culture, Signe Laval and Culture Mauricie are run and verified the data upload has the new domain (lod.footlight.io).
