### ISSUE TITLE
Merge CMS files before pushing to Artsdata

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-footlight#18]
Artsdata would like to validate the data from each CMS calendar and receive a single artifact with all the data.

Currently CMS pushes 4 different artifacts to Artsdata: events, places, people, organizations, taxonomies. The validation of the events artifact often has validation errors because the events have location URIs and do not include the nested Place details and are thus missing postal address.

Expected behaviour: CMS merges events, places, people, organizations, taxonomies in RDF (concatenate the files) and pushes a single artifact to Artsdata using the calendar slug as the artifact name (i.e. `tout-culture`).  This will remove many validation errors as all the data will be available for SHACL to verify, and it will be in a single graph in Artsdata.

Note: Please apply 'DRY' principles to the workflows, and think about how the Artsdata data pipeline Action could incorporate these workflows in the future phase 3 or after.

**Comment by saumier** [comment]
@dev-aravind Thanks for creating the reusable workflow to minimize code repetition. Much better.  I renamed the files from export-tout-culture-entities-to-**footlight**.yml to export-tout-culture-entities-to-**artsdata**.yml.

There is another problem: places with properties with different language tags are not getting exported.  Take a look at this error:

Data in CMS:
https://cms.footlight.io/dashboard/63457978637093005071a053/places/6605a352140606006460d1d5

Data in Artsdata:
https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Flod.footlight.io%2Fresource%2F6605a352140606006460d1c9

Please check the OntoRefine configuration for Places and add multiple language support or find out why the address data in CMS is not getting exported.

**Comment by saumier** [comment]
@dev-aravind I am lowering the priority of this and I would like to understand more before you proceed. Perhaps we can meet one day after the standup. Also, I am wondering how you managed to add the missing data here without using the Databus? https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Flod.footlight.io%2Fresource%2F6605a352140606006460d1c9

Please correct my understanding when it is wrong. The config for OntoRefine should import both en and fr. This should be for all entities with literals. The Open API should be automatically converting the internal @none label to fill in the missing languages depending on the number of languages configured in the calendar and the fallbacks.

**Comment by dev-aravind** [comment]
Task for @dev-aravind 

- [ ] Turn on enableLabelFallback for all calendars
- [ ] Update artsdata-planet-footlight to import english and french literals

**Comment by dev-aravind** [comment]
@saumier The configuration is now updated to import the add-column steps dynamically. Please review this and let me know if you need any changes.

**Comment by saumier** [comment]
@dev-aravind I have looked into the configurations and I don't think we have arrived at the best solution yet.  You did exactly what we discussed by creating a separate add-column json and concatenating them in both the workflow and the shell script. So good work for doing that and thank-you. However, I don't think we have not succeeded in simplifying the whole process.  I think we can design a better and cleaner approach that will be easier for another developer to understand and maintain. Currently, we have a hybrid of creating steps with new columns, and using GRELs in much of the mapping file. The more I see this advancing, the more I think this approach will get exponentially more complicated with each language we add. 

Let's go back to original problem. The original problem arose from needing to support calendars with different languages.  The data being loaded had a different number of columns, so we first added GRELs with IF statements. This made the mapping file difficult to work with, so we then tried to replace the GRELs by creating columns using OntoRefine. This was also problematic because the configuration file erased steps if the column already existed. 

What if we solve the problem with a different approach. What if we created a column with just the language tag, instead of a column for each combination of name and language.  For example, instead of `name_en` and `name_fr` we have `name_value` and `name_language`.   This would remove the need for GRELs with IF statements for each language and remove the need to create missing columns, and reduce the lines in the OntoRefine RDF mapping.  It would also scale really well if we add an additional language like Japanese. Note, we MAY still need a GREL to handle the absence of any language tag, but this would be acceptable and not depend on the number of languages.

Change the input JSON from:
```

 "name": {
                "en": "Centre communautaire Laval-Ouest",
                "fr": "Centre communautaire Laval-Ouest"
            }

```
To
```
 "name": [
                { "value": "Centre communautaire Laval-Ouest", "language:":"en"},
                { "value": "Centre communautaire Laval-Ouest", "language:":"fr"}
            ]
```

In the CSV file this will always create 2 columns: name_value and name_language independent from the number of languages are added. 

Let me know what you think? If you agree this is worth pursuing we can decide to either convert the JSON in the workflow or work with Suhail to output the JSON from CMS in this expanded form.

I also noted that the Event mapping can be simplified since we are already exporting places, people, orgs and concepts separately.  An event only needs the URI of a place, person, org or concept. So location, performer, organizer only need URIs, and all the nested properties can be removed. Also the Concept properties within the Event mapping can be removed as well. To my knowledge only virtual locations and offers need to be nested inside events and therefore should continue to be included with events.

This is a lot of change. I hope you are not discouraged. I am a strong believer in finding the most elegant solution based on the needs of the big picture.  In our case, I know we will be adding more languages so I think this is the right moment to really find the most elegant approach.

**Comment by saumier** [comment]
@sahalali @dev-aravind I would like you to discuss between each other the 2 approaches of exporting data from CMS to Artsdata, taking into account multiple languages. custom properties created in taxonomies, and sub-events. Please read my long comment above as well.

1. Export using OntoRefine with a language column (not hard coded) and new CMS API to export sub-event JSON.
2. Export JSON-LD directly from CMS.
